### ISSUE TITLE
Link to GoDocs - 404

### ISSUE THREAD

**Issue by chrismclaughlin55** [gofan1776/safe_panic#1]
The link in the Readme doesnt resolve to the proper godocs. This is the link in reference:
https://godoc.org/gofan1776/safe_panic

**Comment by gofan1776** [comment]
dang it! i'll email the mainainers and alert them to the bug in godoc's code. thanks!

**Comment by gofan1776** [comment]
oh silly me turns out i forgot the full url. thanks again!
